CREATE DATABASE GSS;
USE GSS;

CREATE TABLE Cadastro(
idCadastro INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR (100),
Email VARCHAR(100),
CPF VARCHAR(11),
Senha VARCHAR(50)
);

CREATE TABLE Login(
idUsuario INT PRIMARY KEY AUTO_INCREMENT,
Email VARCHAR(100),
Senha VARCHAR(50),
fkCadastro INT,
CONSTRAINT fkCadastroLogin FOREIGN KEY (fkCadastro) REFERENCES Cadastro (idCadastro)
);

CREATE TABLE Nivelamento(
idNivelamento INT PRIMARY KEY AUTO_INCREMENT,
Nivel VARCHAR(30)
);